stages:
  - check
  - build
  - test
  - deploy

.rust-default:
  image: rust:latest
  tags:
    - linux
    - docker
  cache:
    - key: $CI_COMMIT_REF
      paths: [ target/ ]
    - key: cargo
      paths: [ cargo/ ]
  interruptible: true
  timeout: 30m
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
    CACHE_FALLBACK_KEY: $CI_DEFAULT_BRANCH
  before_script:
    - rustup --version && rustc --version && cargo --version && echo $RUSTFLAGS && echo $CARGO_OPTS


check_format:
  extends: .rust-default
  stage: check
  script:
    - rustup component add rustfmt
    - cargo fmt --check

lint:
  extends: .rust-default
  stage: check
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

build:
  extends: .rust-default
  stage: build
  before_script:
    - rustup target add aarch64-unknown-linux-gnu
  script:
    - 'cargo +stable build 
      --verbose 
      --color always 
      --release
      --target x86_64-unknown-linux-gnu 
      --target aarch64-unknown-linux-gnu'
  artifacts:
    paths:
      - target/*/release/iris_backend

test:
  extends: .rust-default
  stage: test
  needs: [ build ]
  script:
    - 'cargo +nightly test 
      --verbose 
      --color always 
      -- 
      -Z unstable-options 
      --format junit > results.xml'
  artifacts:
    when: always
    reports:
      junit: results.xml

docker_build_deploy:
  stage: deploy
  tags:
    - shell
  dependencies:
    - build
  before_script:
    - mkdir -p output/arm64
    - mkdir -p output/amd64
    - mv target/aarch64-unknown-linux-gnu/release/iris_backend output/arm64/iris_backend
    - mv target/x86_64-unknown-linux-gnu/release/iris_backend output/amd64/iris_backend
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - 'docker buildx build 
      -t $CI_REGISTRY:latest
      -t $CI_REGISTRY:$CI_COMMIT_SHORT_SHA
      . 
      --platform linux/amd64,linux/arm64 
      --builder=crossplatform 
      --file docker/Dockerfile 
      --push'